---
  - name: Set Jenkins IP as a fact
    set_fact:
      jenkins_ip: 44.243.104.124
    become: true

  - name: Install Docker
    apt:
      name: docker.io
      state: present
    
  - name: Create /var/jenkins_home
    file:
      name: /var/jenkins_home
      state: directory

  - name: Set directory Permissions
    shell: chown -R 1000:1000 /var/jenkins_home

  - name: Download java jar file 
    apt:
     name: openjdk-8-jdk
     state: present

  - name: Run Jenkins Container
    docker_container:
      name: jenkins
      image: jenkins/jenkins
      state: started
      restart_policy: always
      ports:
        - "8080:8080"
      volumes:
        - /var/jenkins_home:/var/jenkins_home